---
- name: Replace lines
  hosts: localhost
  gather_facts: yes
  become: no
  tasks:
    - name: Replace a private IP entry by "master-1" hostname in admin.conf
      lineinfile:
        dest: "{{ artifacts_dir }}admin.conf"
        regexp: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}
        line: "    server: https://master-1:6443"
        state: present

    - name: Copy admin.conf as ~/.kube/config
      copy:
        src: "{{ artifacts_dir }}admin.conf"
        dest: "{{artifacts_dir}}config"

    - name: Add a line in /etc/hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: master-1
        line: "{{hostvars['master-1']['ansible_host']}} master-1"
        state: present

    - name: Bash autocomplition
      lineinfile:
        path: ~/.bashrc
        line: source <(kubectl completion bash)
        state: present
